indexPath: "/Users/wuxiaoming/IdeaProjects/hoytNote/index"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/note
    username: dev
    password: devdev
#    driver-class-name: com.mysql.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include:
        - "httptrace"
        - "*"
        include=httptrace:

logging.level.org.springframework.web: TRACE
